# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    
    # Publish Windows app
    - name: Publish Windows App
      run: dotnet publish --configuration Release /p:PublishProfile=Publish-win-x64.pubxml --output ./publish/windows/
      working-directory: src/google-photos-upload
    
    # Publish cross-platform app
    - name: Publish cross-platform App
      run: dotnet publish --configuration Release /p:PublishProfile=Publish-portable.pubxml --output ./publish/cross-platform/
      working-directory: src/google-photos-upload
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: google-photos-upload-app-windows
        path: src/google-photos-upload/publish/windows/
        retention-days: 30
    
    - name: Upload cross-platform executable
      uses: actions/upload-artifact@v4
      with:
        name: google-photos-upload-app-cross-platform
        path: src/google-photos-upload/publish/cross-platform/
        retention-days: 30